export const tasks = [
  {
    id: 1,
    title: "Learn HTML",
    start_date: "07-07-2023",
    completed: false,
    user: "Aboubacar Sangare",
  },
  {
    id: 2,
    title: "Learn CSS",
    start_date: "07-08-2023",
    completed: false,
    user: "Aboubacar Sangare",
  },
  {
    id: 3,
    title: "Learn Javascript",
    start_date: "07-09-2023",
    completed: false,
    user: "Aboubacar Sangare",
  },
  {
    id: 4,
    title: "Learn React",
    start_date: "07-10-2023",
    completed: false,
    user: "Aboubacar Sangare",
  },
  {
    id: 5,
    title: "Learn Design",
    start_date: "07-07-2023",
    end_date: "07-08-2023",
    completed: true,
    user: "Aboubacar Sangare",
  },
  {
    id: 6,
    title: "Learn VCS (Git, Github, Bitbucket)",
    start_date: "07-08-2023",
    end_date: "07-09-2023",
    completed: true,
    user: "Aboubacar Sangare",
  },
  {
    id: 7,
    title: "Learn Node",
    start_date: "07-09-2023",
    end_date: "07-10-2023",
    completed: true,
    user: "Aboubacar Sangare",
  },
  {
    id: 8,
    title: "Learn PHP",
    start_date: "07-10-2023",
    end_date: "07-11-2023",
    completed: true,
    user: "Aboubacar Sangare",
  },
];
